config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :authorposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t ".blog" %>
    <%= link_to t(".name"), "http://www.facebook.com/deumi.rct" %>
  </small>
  <nav>
    <ul>
      <small>
        <li><%= link_to t(".about"), about_path %></li>
        <li><%= link_to t(".contact"), contact_path %></li>
      </small>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-toggleable-md bg-faded">
    <button class="navbar-toggler navbar-toggler-right" type="button"
      data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" <%= link_to image_tag("home.png"), root_path,
      id: "logo-img" %></a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <form action="users" method="get" class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2 my-lg-2" type="text" name="q">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
          <%= t ".search" %></button>
      </form>
      <ul class="navbar-nav mr-auto">
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <% if logged_in? %>
          <%= link_to t(".users"), users_path, class: "btn btn-outline-info" %>
          <div class="dropdown">
            <a href="#" class="nav-link dropdown-toggle btn btn-outline-primary"
              data-toggle="dropdown">
              <%= t ".hi" %> <%= @current_user.name %>
            </a>
            <ul class="dropdown-menu">
              <li>
                <a class="nav-link" <%= link_to t(".profile"), current_user %>
              </li>
              <li>
                <a class="nav-link" <%= link_to t(".setting"),
                  edit_user_path(current_user) %>
              </li>
              <li>
                <a class="nav-link" <%= link_to t(".log_out"), logout_path,
                  method: :delete %>
              </li>
            </ul>
          </div>
        <% else %>
          <%= link_to t(".log_in"), login_path, class: "btn btn-outline-info" %>
        <% end %>
      </form>
    </div>
  </nav>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "application", media: "all",
  "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= render "layouts/rails_default" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>